# specify here default training configuration
defaults:
  - _self_

project: tuning-competition-baseline  # wandb project name
entity: xxx  # FIXME: wandb entity name

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}     # FIXME: This directory is for storing models and logs. default is the current working directory
data_dir: "./datasets/tuning-competition-datasets"

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# name of the run is accessed by loggers
# should be used along with experiment mode
exp_dir: ${work_dir}/result
run_dir: ${exp_dir}/${now:%m%d}_${now:%H%M%S}
config_name: ${hydra:job.config_name}

name: ${config_name}-${now:%Y%m%d}_${now:%H%M%S}

hydra:
  run:
    dir: ${exp_dir}
  sweep:
    dir: ${work_dir}/multirun_result
    subdir: ${name}-${hydra:job.num}
  job:
    env_set:
      TOKENIZERS_PARALLELISM: false
      HF_HOME: /path/to/your/hf_home  # FIXME: This directory is for storing Hugging Face models
      TMPDIR: /path/to/your/tmp # FIXME: This directory is for storing temporary files
    config:
      override_dirname:
        kv_sep: ':'
        item_sep: '-'
        exclude_keys:
          - seed
          - name
          - exp_dir
          - run_dir
          - logger
          - per_device_train_batch_size
          - per_device_eval_batch_size
          - gradient_checkpointing
          - logging_steps
          - eval_steps
          - save_steps
          - trainer.num_nodes
          - use_mpi
          - use_slurm
